apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
  namespace: mini

spec:
  storageClassName: redis-ebs
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 5Gi