apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: cart-network-policy
  namespace: mini
spec:
  podSelector:
    matchLabels:
      app: cart-service

  policyTypes:
    - Ingress

  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: frontend
      ports:
        - protocol: TCP
          port: 5002