apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: {{ .Values.namespace }}

spec:
  selector:
    app: frontend

  ports:
    - port: 5003
      targetPort: 5003
      protocol: TCP

  type: ClusterIP