apiVersion: v1
kind: ConfigMap
metadata:
  name: product-config
  namespace: mini

data:
  AWS_REGION: "ap-south-2"
  DYNAMODB_TABLE_NAME: "mini-amazon-products"
  S3_BUCKET_NAME: "mini-amazon-product-images"