apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: mini

spec:
  replicas: 2

  selector:
    matchLabels:
      app: user-service

  template:
    metadata:
      labels:
        app: user-service

    spec:
      containers:
        - name: user-service
          image: girijos/mini-amazon-user-service:1.0

          ports:
            - containerPort: 5000

          envFrom:
            - configMapRef:
                name: user-config

            - secretRef:
                name: user-secret

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"

            limits:
              cpu: "250m"
              memory: "256Mi"

          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 20
            periodSeconds: 20